name       : haskell-glib
version    : 0.13.8.1
release    : 6
source     :
    - https://hackage.haskell.org/package/glib-0.13.8.1/glib-0.13.8.1.tar.gz : dcd028ac6d4a7476c14585be1d845b8c4aea4c389f34e809ed1a8df7425c1a9c
license    : LGPL-2.1-only
component  : programming.haskell
summary    : GLib is a collection of C data structures and utility functions for the GObject system, main loop implementation, for strings and common data structures dealing with Unicode. This package only binds as much functionality as required to support the packages that wrap libraries that are themselves based on GLib.
description: |
    GLib is a collection of C data structures and utility functions for the GObject system, main loop implementation, for strings and common data structures dealing with Unicode. This package only binds as much functionality as required to support the packages that wrap libraries that are themselves based on GLib.
builddeps  :
    - gtk2hs-buildtools-devel # not in .cabal
    - haskell-cabal-install
    - haskell-hashtables-devel
    - haskell-utf8-string-devel
rundeps    :
    - devel:
        - gtk2hs-buildtools-devel # not in .cabal
        - haskell-cabal-install
        - haskell-hashtables-devel
        - haskell-utf8-string-devel
optimize   : no-symbols
networking : yes
setup      : |
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
