name       : haskell-glib
version    : 0.13.4.1
release    : 1
source     :
    - http://hackage.haskell.org/package/glib-0.13.4.1/glib-0.13.4.1.tar.gz : f57202ed4094cc50caa8b390c8b78a1620b3c43b913edb1e5bda0f3c5be32630
license    : LGPL-2.1
component  : programming.haskell
summary    : GLib is a collection of C data structures and utility functions for the GObject system, main loop implementation, for strings and common data structures dealing with Unicode. This package only binds as much functionality as required to support the packages that wrap libraries that are themselves based on GLib.
description: |
    GLib is a collection of C data structures and utility functions for the GObject system, main loop implementation, for strings and common data structures dealing with Unicode. This package only binds as much functionality as required to support the packages that wrap libraries that are themselves based on GLib.
builddeps  :
    - pkgconfig(glib-2.0)
    - ghc-devel
    - gtk2hs-buildtools-devel
    - haskell-cabal-install
    - haskell-hashable-devel
    - haskell-hashtables-devel
    - haskell-primitive-devel
    - haskell-random-devel
    - haskell-text-devel
    - haskell-utf8-string
    - haskell-vector-devel
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
