name       : haskell-glib
version    : 0.13.6.0
release    : 5
source     :
    - https://hackage.haskell.org/package/glib-0.13.6.0/glib-0.13.6.0.tar.gz : 4e71062c6a458440294d820e21449aa4666deed2ea233ef5915da7c1d4aee8eb
license    : LGPL-2.1
component  : programming.haskell
summary    : GLib is a collection of C data structures and utility functions for the
    GObject system, main loop implementation, for strings and common data structures
    dealing with Unicode. This package only binds as much functionality as required
    to support the packages that wrap libraries that are themselves based on GLib.
description: |
    GLib is a collection of C data structures and utility functions for the GObject system, main loop implementation, for strings and common data structures dealing with Unicode. This package only binds as much functionality as required to support the packages that wrap libraries that are themselves based on GLib.
builddeps  :
    - pkgconfig(glib-2.0)
    - ghc-devel
    - gtk2hs-buildtools-devel
    - haskell-cabal-install
    - haskell-hashable-devel
    - haskell-hashtables-devel
    - haskell-primitive-devel
    - haskell-random-devel
    - haskell-text-devel
    - haskell-utf8-string
    - haskell-vector-devel
optimize   : no-symbols
networking : yes
setup      : |
    # sed -i "s|Custom|Simple|" glib.cabal
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
